dist: xenial
language: cpp

addons:
  apt:
    packages:
      - clang
      - libc++-dev
      - libhdf5-dev

stages:
  - test

jobs:
  include:
    - stage: test
      name: g++
      script: make -C tests -j 2

    - stage: test
      name: clang++
      env:
        - HDF5_CXX=clang++
        - HDF5_CLINKER=clang++
      script: make -C tests -j 2 EXTRA_CXXFLAGS=-stdlib=libc++
