dist: xenial
language: cpp

addons:
  apt:
    packages:
      - clang
      - libc++-dev
      - libhdf5-dev

stages:
  - test

jobs:
  include:
    - stage: test
      name: g++
      script: env HDF5_CXX=g++ make -C tests -j 2

    - stage: test
      name: clang++
      script: env HDF5_CXX=clang++ make -C tests -j 2 EXTRA_CXXFLAGS=-stdlib=libc++
